/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AgencesRouteImport } from './routes/agences'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as InscriptionAgenceRouteImport } from './routes/inscription-agence'
import { Route as InscriptionClientRouteImport } from './routes/inscription-client'
import { Route as PostulerUnProjetRouteImport } from './routes/postuler-un-projet'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as AgencesIdRouteImport } from './routes/agences.$id'
import { Route as FonctionnalitesSlugRouteImport } from './routes/fonctionnalites.$slug'
import { Route as AuthenticatedAgenceAnalyticsRouteImport } from './routes/_authenticated/agence.analytics'
import { Route as AuthenticatedAgenceFacturationRouteImport } from './routes/_authenticated/agence.facturation'
import { Route as AuthenticatedAgenceMesProspectionsRouteImport } from './routes/_authenticated/agence.mes-prospections'
import { Route as AuthenticatedAgenceNotificationsRouteImport } from './routes/_authenticated/agence.notifications'
import { Route as AuthenticatedAgenceOpportunitesRouteImport } from './routes/_authenticated/agence.opportunites'
import { Route as AuthenticatedAgenceParametresRouteImport } from './routes/_authenticated/agence.parametres'
import { Route as AuthenticatedAgenceProfilRouteImport } from './routes/_authenticated/agence.profil'
import { Route as AuthenticatedAgenceProjetsEnCoursRouteImport } from './routes/_authenticated/agence.projets-en-cours'
import { Route as AuthenticatedAgenceProspectionRouteImport } from './routes/_authenticated/agence.prospection'
import { Route as AuthenticatedAgenceSuspensionRouteImport } from './routes/_authenticated/agence.suspension'
import { Route as AuthenticatedAgenceTableauDeBordRouteImport } from './routes/_authenticated/agence.tableau-de-bord'
import { Route as AuthenticatedAgenceWorkflowRouteImport } from './routes/_authenticated/agence.workflow'
import { Route as AuthenticatedClientCollaborationsRouteImport } from './routes/_authenticated/client.collaborations'
import { Route as AuthenticatedClientMesProjetsRouteImport } from './routes/_authenticated/client.mes-projets'
import { Route as AuthenticatedClientMonProfilRouteImport } from './routes/_authenticated/client.mon-profil'
import { Route as AuthenticatedClientNotificationsRouteImport } from './routes/_authenticated/client.notifications'
import { Route as AuthenticatedClientParametresRouteImport } from './routes/_authenticated/client.parametres'
import { Route as AuthenticatedClientPostulerUnProjetRouteImport } from './routes/_authenticated/client.postuler-un-projet'
import { Route as AuthenticatedClientTableauDeBordRouteImport } from './routes/_authenticated/client.tableau-de-bord'
import { Route as AuthenticatedClientMesProjetsIdRouteImport } from './routes/_authenticated/client.mes-projets.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencesRoute = AgencesRouteImport.update({
  id: '/agences',
  path: '/agences',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionAgenceRoute = InscriptionAgenceRouteImport.update({
  id: '/inscription-agence',
  path: '/inscription-agence',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionClientRoute = InscriptionClientRouteImport.update({
  id: '/inscription-client',
  path: '/inscription-client',
  getParentRoute: () => rootRouteImport,
} as any)
const PostulerUnProjetRoute = PostulerUnProjetRouteImport.update({
  id: '/postuler-un-projet',
  path: '/postuler-un-projet',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencesIdRoute = AgencesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgencesRoute,
} as any)
const FonctionnalitesSlugRoute = FonctionnalitesSlugRouteImport.update({
  id: '/fonctionnalites/$slug',
  path: '/fonctionnalites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgenceAnalyticsRoute =
  AuthenticatedAgenceAnalyticsRouteImport.update({
    id: '/agence/analytics',
    path: '/agence/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceFacturationRoute =
  AuthenticatedAgenceFacturationRouteImport.update({
    id: '/agence/facturation',
    path: '/agence/facturation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceMesProspectionsRoute =
  AuthenticatedAgenceMesProspectionsRouteImport.update({
    id: '/agence/mes-prospections',
    path: '/agence/mes-prospections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceNotificationsRoute =
  AuthenticatedAgenceNotificationsRouteImport.update({
    id: '/agence/notifications',
    path: '/agence/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceOpportunitesRoute =
  AuthenticatedAgenceOpportunitesRouteImport.update({
    id: '/agence/opportunites',
    path: '/agence/opportunites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceParametresRoute =
  AuthenticatedAgenceParametresRouteImport.update({
    id: '/agence/parametres',
    path: '/agence/parametres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceProfilRoute =
  AuthenticatedAgenceProfilRouteImport.update({
    id: '/agence/profil',
    path: '/agence/profil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceProjetsEnCoursRoute =
  AuthenticatedAgenceProjetsEnCoursRouteImport.update({
    id: '/agence/projets-en-cours',
    path: '/agence/projets-en-cours',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceProspectionRoute =
  AuthenticatedAgenceProspectionRouteImport.update({
    id: '/agence/prospection',
    path: '/agence/prospection',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceSuspensionRoute =
  AuthenticatedAgenceSuspensionRouteImport.update({
    id: '/agence/suspension',
    path: '/agence/suspension',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceTableauDeBordRoute =
  AuthenticatedAgenceTableauDeBordRouteImport.update({
    id: '/agence/tableau-de-bord',
    path: '/agence/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceWorkflowRoute =
  AuthenticatedAgenceWorkflowRouteImport.update({
    id: '/agence/workflow',
    path: '/agence/workflow',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientCollaborationsRoute =
  AuthenticatedClientCollaborationsRouteImport.update({
    id: '/client/collaborations',
    path: '/client/collaborations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientMesProjetsRoute =
  AuthenticatedClientMesProjetsRouteImport.update({
    id: '/client/mes-projets',
    path: '/client/mes-projets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientMonProfilRoute =
  AuthenticatedClientMonProfilRouteImport.update({
    id: '/client/mon-profil',
    path: '/client/mon-profil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientNotificationsRoute =
  AuthenticatedClientNotificationsRouteImport.update({
    id: '/client/notifications',
    path: '/client/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientParametresRoute =
  AuthenticatedClientParametresRouteImport.update({
    id: '/client/parametres',
    path: '/client/parametres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientPostulerUnProjetRoute =
  AuthenticatedClientPostulerUnProjetRouteImport.update({
    id: '/client/postuler-un-projet',
    path: '/client/postuler-un-projet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientTableauDeBordRoute =
  AuthenticatedClientTableauDeBordRouteImport.update({
    id: '/client/tableau-de-bord',
    path: '/client/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientMesProjetsIdRoute =
  AuthenticatedClientMesProjetsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedClientMesProjetsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agences': typeof AgencesRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/inscription-agence': typeof InscriptionAgenceRoute
  '/inscription-client': typeof InscriptionClientRoute
  '/postuler-un-projet': typeof PostulerUnProjetRoute
  '/projets': typeof ProjetsRoute
  '/agences/$id': typeof AgencesIdRoute
  '/fonctionnalites/$slug': typeof FonctionnalitesSlugRoute
  '/agence/analytics': typeof AuthenticatedAgenceAnalyticsRoute
  '/agence/facturation': typeof AuthenticatedAgenceFacturationRoute
  '/agence/mes-prospections': typeof AuthenticatedAgenceMesProspectionsRoute
  '/agence/notifications': typeof AuthenticatedAgenceNotificationsRoute
  '/agence/opportunites': typeof AuthenticatedAgenceOpportunitesRoute
  '/agence/parametres': typeof AuthenticatedAgenceParametresRoute
  '/agence/profil': typeof AuthenticatedAgenceProfilRoute
  '/agence/projets-en-cours': typeof AuthenticatedAgenceProjetsEnCoursRoute
  '/agence/prospection': typeof AuthenticatedAgenceProspectionRoute
  '/agence/suspension': typeof AuthenticatedAgenceSuspensionRoute
  '/agence/tableau-de-bord': typeof AuthenticatedAgenceTableauDeBordRoute
  '/agence/workflow': typeof AuthenticatedAgenceWorkflowRoute
  '/client/collaborations': typeof AuthenticatedClientCollaborationsRoute
  '/client/mes-projets': typeof AuthenticatedClientMesProjetsRouteWithChildren
  '/client/mon-profil': typeof AuthenticatedClientMonProfilRoute
  '/client/notifications': typeof AuthenticatedClientNotificationsRoute
  '/client/parametres': typeof AuthenticatedClientParametresRoute
  '/client/postuler-un-projet': typeof AuthenticatedClientPostulerUnProjetRoute
  '/client/tableau-de-bord': typeof AuthenticatedClientTableauDeBordRoute
  '/client/mes-projets/$id': typeof AuthenticatedClientMesProjetsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agences': typeof AgencesRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/inscription-agence': typeof InscriptionAgenceRoute
  '/inscription-client': typeof InscriptionClientRoute
  '/postuler-un-projet': typeof PostulerUnProjetRoute
  '/projets': typeof ProjetsRoute
  '/agences/$id': typeof AgencesIdRoute
  '/fonctionnalites/$slug': typeof FonctionnalitesSlugRoute
  '/agence/analytics': typeof AuthenticatedAgenceAnalyticsRoute
  '/agence/facturation': typeof AuthenticatedAgenceFacturationRoute
  '/agence/mes-prospections': typeof AuthenticatedAgenceMesProspectionsRoute
  '/agence/notifications': typeof AuthenticatedAgenceNotificationsRoute
  '/agence/opportunites': typeof AuthenticatedAgenceOpportunitesRoute
  '/agence/parametres': typeof AuthenticatedAgenceParametresRoute
  '/agence/profil': typeof AuthenticatedAgenceProfilRoute
  '/agence/projets-en-cours': typeof AuthenticatedAgenceProjetsEnCoursRoute
  '/agence/prospection': typeof AuthenticatedAgenceProspectionRoute
  '/agence/suspension': typeof AuthenticatedAgenceSuspensionRoute
  '/agence/tableau-de-bord': typeof AuthenticatedAgenceTableauDeBordRoute
  '/agence/workflow': typeof AuthenticatedAgenceWorkflowRoute
  '/client/collaborations': typeof AuthenticatedClientCollaborationsRoute
  '/client/mes-projets': typeof AuthenticatedClientMesProjetsRouteWithChildren
  '/client/mon-profil': typeof AuthenticatedClientMonProfilRoute
  '/client/notifications': typeof AuthenticatedClientNotificationsRoute
  '/client/parametres': typeof AuthenticatedClientParametresRoute
  '/client/postuler-un-projet': typeof AuthenticatedClientPostulerUnProjetRoute
  '/client/tableau-de-bord': typeof AuthenticatedClientTableauDeBordRoute
  '/client/mes-projets/$id': typeof AuthenticatedClientMesProjetsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agences': typeof AgencesRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/inscription-agence': typeof InscriptionAgenceRoute
  '/inscription-client': typeof InscriptionClientRoute
  '/postuler-un-projet': typeof PostulerUnProjetRoute
  '/projets': typeof ProjetsRoute
  '/agences/$id': typeof AgencesIdRoute
  '/fonctionnalites/$slug': typeof FonctionnalitesSlugRoute
  '/_authenticated/agence/analytics': typeof AuthenticatedAgenceAnalyticsRoute
  '/_authenticated/agence/facturation': typeof AuthenticatedAgenceFacturationRoute
  '/_authenticated/agence/mes-prospections': typeof AuthenticatedAgenceMesProspectionsRoute
  '/_authenticated/agence/notifications': typeof AuthenticatedAgenceNotificationsRoute
  '/_authenticated/agence/opportunites': typeof AuthenticatedAgenceOpportunitesRoute
  '/_authenticated/agence/parametres': typeof AuthenticatedAgenceParametresRoute
  '/_authenticated/agence/profil': typeof AuthenticatedAgenceProfilRoute
  '/_authenticated/agence/projets-en-cours': typeof AuthenticatedAgenceProjetsEnCoursRoute
  '/_authenticated/agence/prospection': typeof AuthenticatedAgenceProspectionRoute
  '/_authenticated/agence/suspension': typeof AuthenticatedAgenceSuspensionRoute
  '/_authenticated/agence/tableau-de-bord': typeof AuthenticatedAgenceTableauDeBordRoute
  '/_authenticated/agence/workflow': typeof AuthenticatedAgenceWorkflowRoute
  '/_authenticated/client/collaborations': typeof AuthenticatedClientCollaborationsRoute
  '/_authenticated/client/mes-projets': typeof AuthenticatedClientMesProjetsRouteWithChildren
  '/_authenticated/client/mon-profil': typeof AuthenticatedClientMonProfilRoute
  '/_authenticated/client/notifications': typeof AuthenticatedClientNotificationsRoute
  '/_authenticated/client/parametres': typeof AuthenticatedClientParametresRoute
  '/_authenticated/client/postuler-un-projet': typeof AuthenticatedClientPostulerUnProjetRoute
  '/_authenticated/client/tableau-de-bord': typeof AuthenticatedClientTableauDeBordRoute
  '/_authenticated/client/mes-projets/$id': typeof AuthenticatedClientMesProjetsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agences'
    | '/connexion'
    | '/inscription-agence'
    | '/inscription-client'
    | '/postuler-un-projet'
    | '/projets'
    | '/agences/$id'
    | '/fonctionnalites/$slug'
    | '/agence/analytics'
    | '/agence/facturation'
    | '/agence/mes-prospections'
    | '/agence/notifications'
    | '/agence/opportunites'
    | '/agence/parametres'
    | '/agence/profil'
    | '/agence/projets-en-cours'
    | '/agence/prospection'
    | '/agence/suspension'
    | '/agence/tableau-de-bord'
    | '/agence/workflow'
    | '/client/collaborations'
    | '/client/mes-projets'
    | '/client/mon-profil'
    | '/client/notifications'
    | '/client/parametres'
    | '/client/postuler-un-projet'
    | '/client/tableau-de-bord'
    | '/client/mes-projets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agences'
    | '/connexion'
    | '/inscription-agence'
    | '/inscription-client'
    | '/postuler-un-projet'
    | '/projets'
    | '/agences/$id'
    | '/fonctionnalites/$slug'
    | '/agence/analytics'
    | '/agence/facturation'
    | '/agence/mes-prospections'
    | '/agence/notifications'
    | '/agence/opportunites'
    | '/agence/parametres'
    | '/agence/profil'
    | '/agence/projets-en-cours'
    | '/agence/prospection'
    | '/agence/suspension'
    | '/agence/tableau-de-bord'
    | '/agence/workflow'
    | '/client/collaborations'
    | '/client/mes-projets'
    | '/client/mon-profil'
    | '/client/notifications'
    | '/client/parametres'
    | '/client/postuler-un-projet'
    | '/client/tableau-de-bord'
    | '/client/mes-projets/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agences'
    | '/connexion'
    | '/inscription-agence'
    | '/inscription-client'
    | '/postuler-un-projet'
    | '/projets'
    | '/agences/$id'
    | '/fonctionnalites/$slug'
    | '/_authenticated/agence/analytics'
    | '/_authenticated/agence/facturation'
    | '/_authenticated/agence/mes-prospections'
    | '/_authenticated/agence/notifications'
    | '/_authenticated/agence/opportunites'
    | '/_authenticated/agence/parametres'
    | '/_authenticated/agence/profil'
    | '/_authenticated/agence/projets-en-cours'
    | '/_authenticated/agence/prospection'
    | '/_authenticated/agence/suspension'
    | '/_authenticated/agence/tableau-de-bord'
    | '/_authenticated/agence/workflow'
    | '/_authenticated/client/collaborations'
    | '/_authenticated/client/mes-projets'
    | '/_authenticated/client/mon-profil'
    | '/_authenticated/client/notifications'
    | '/_authenticated/client/parametres'
    | '/_authenticated/client/postuler-un-projet'
    | '/_authenticated/client/tableau-de-bord'
    | '/_authenticated/client/mes-projets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgencesRoute: typeof AgencesRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  InscriptionAgenceRoute: typeof InscriptionAgenceRoute
  InscriptionClientRoute: typeof InscriptionClientRoute
  PostulerUnProjetRoute: typeof PostulerUnProjetRoute
  ProjetsRoute: typeof ProjetsRoute
  FonctionnalitesSlugRoute: typeof FonctionnalitesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agences': {
      id: '/agences'
      path: '/agences'
      fullPath: '/agences'
      preLoaderRoute: typeof AgencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription-agence': {
      id: '/inscription-agence'
      path: '/inscription-agence'
      fullPath: '/inscription-agence'
      preLoaderRoute: typeof InscriptionAgenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription-client': {
      id: '/inscription-client'
      path: '/inscription-client'
      fullPath: '/inscription-client'
      preLoaderRoute: typeof InscriptionClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postuler-un-projet': {
      id: '/postuler-un-projet'
      path: '/postuler-un-projet'
      fullPath: '/postuler-un-projet'
      preLoaderRoute: typeof PostulerUnProjetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agences/$id': {
      id: '/agences/$id'
      path: '/$id'
      fullPath: '/agences/$id'
      preLoaderRoute: typeof AgencesIdRouteImport
      parentRoute: typeof AgencesRoute
    }
    '/fonctionnalites/$slug': {
      id: '/fonctionnalites/$slug'
      path: '/fonctionnalites/$slug'
      fullPath: '/fonctionnalites/$slug'
      preLoaderRoute: typeof FonctionnalitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agence/analytics': {
      id: '/_authenticated/agence/analytics'
      path: '/agence/analytics'
      fullPath: '/agence/analytics'
      preLoaderRoute: typeof AuthenticatedAgenceAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/facturation': {
      id: '/_authenticated/agence/facturation'
      path: '/agence/facturation'
      fullPath: '/agence/facturation'
      preLoaderRoute: typeof AuthenticatedAgenceFacturationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/mes-prospections': {
      id: '/_authenticated/agence/mes-prospections'
      path: '/agence/mes-prospections'
      fullPath: '/agence/mes-prospections'
      preLoaderRoute: typeof AuthenticatedAgenceMesProspectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/notifications': {
      id: '/_authenticated/agence/notifications'
      path: '/agence/notifications'
      fullPath: '/agence/notifications'
      preLoaderRoute: typeof AuthenticatedAgenceNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/opportunites': {
      id: '/_authenticated/agence/opportunites'
      path: '/agence/opportunites'
      fullPath: '/agence/opportunites'
      preLoaderRoute: typeof AuthenticatedAgenceOpportunitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/parametres': {
      id: '/_authenticated/agence/parametres'
      path: '/agence/parametres'
      fullPath: '/agence/parametres'
      preLoaderRoute: typeof AuthenticatedAgenceParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/profil': {
      id: '/_authenticated/agence/profil'
      path: '/agence/profil'
      fullPath: '/agence/profil'
      preLoaderRoute: typeof AuthenticatedAgenceProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/projets-en-cours': {
      id: '/_authenticated/agence/projets-en-cours'
      path: '/agence/projets-en-cours'
      fullPath: '/agence/projets-en-cours'
      preLoaderRoute: typeof AuthenticatedAgenceProjetsEnCoursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/prospection': {
      id: '/_authenticated/agence/prospection'
      path: '/agence/prospection'
      fullPath: '/agence/prospection'
      preLoaderRoute: typeof AuthenticatedAgenceProspectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/suspension': {
      id: '/_authenticated/agence/suspension'
      path: '/agence/suspension'
      fullPath: '/agence/suspension'
      preLoaderRoute: typeof AuthenticatedAgenceSuspensionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/tableau-de-bord': {
      id: '/_authenticated/agence/tableau-de-bord'
      path: '/agence/tableau-de-bord'
      fullPath: '/agence/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedAgenceTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/workflow': {
      id: '/_authenticated/agence/workflow'
      path: '/agence/workflow'
      fullPath: '/agence/workflow'
      preLoaderRoute: typeof AuthenticatedAgenceWorkflowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/collaborations': {
      id: '/_authenticated/client/collaborations'
      path: '/client/collaborations'
      fullPath: '/client/collaborations'
      preLoaderRoute: typeof AuthenticatedClientCollaborationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/mes-projets': {
      id: '/_authenticated/client/mes-projets'
      path: '/client/mes-projets'
      fullPath: '/client/mes-projets'
      preLoaderRoute: typeof AuthenticatedClientMesProjetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/mon-profil': {
      id: '/_authenticated/client/mon-profil'
      path: '/client/mon-profil'
      fullPath: '/client/mon-profil'
      preLoaderRoute: typeof AuthenticatedClientMonProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/notifications': {
      id: '/_authenticated/client/notifications'
      path: '/client/notifications'
      fullPath: '/client/notifications'
      preLoaderRoute: typeof AuthenticatedClientNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/parametres': {
      id: '/_authenticated/client/parametres'
      path: '/client/parametres'
      fullPath: '/client/parametres'
      preLoaderRoute: typeof AuthenticatedClientParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/postuler-un-projet': {
      id: '/_authenticated/client/postuler-un-projet'
      path: '/client/postuler-un-projet'
      fullPath: '/client/postuler-un-projet'
      preLoaderRoute: typeof AuthenticatedClientPostulerUnProjetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/tableau-de-bord': {
      id: '/_authenticated/client/tableau-de-bord'
      path: '/client/tableau-de-bord'
      fullPath: '/client/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedClientTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/mes-projets/$id': {
      id: '/_authenticated/client/mes-projets/$id'
      path: '/$id'
      fullPath: '/client/mes-projets/$id'
      preLoaderRoute: typeof AuthenticatedClientMesProjetsIdRouteImport
      parentRoute: typeof AuthenticatedClientMesProjetsRoute
    }
  }
}

interface AuthenticatedClientMesProjetsRouteChildren {
  AuthenticatedClientMesProjetsIdRoute: typeof AuthenticatedClientMesProjetsIdRoute
}

const AuthenticatedClientMesProjetsRouteChildren: AuthenticatedClientMesProjetsRouteChildren =
  {
    AuthenticatedClientMesProjetsIdRoute: AuthenticatedClientMesProjetsIdRoute,
  }

const AuthenticatedClientMesProjetsRouteWithChildren =
  AuthenticatedClientMesProjetsRoute._addFileChildren(
    AuthenticatedClientMesProjetsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgenceAnalyticsRoute: typeof AuthenticatedAgenceAnalyticsRoute
  AuthenticatedAgenceFacturationRoute: typeof AuthenticatedAgenceFacturationRoute
  AuthenticatedAgenceMesProspectionsRoute: typeof AuthenticatedAgenceMesProspectionsRoute
  AuthenticatedAgenceNotificationsRoute: typeof AuthenticatedAgenceNotificationsRoute
  AuthenticatedAgenceOpportunitesRoute: typeof AuthenticatedAgenceOpportunitesRoute
  AuthenticatedAgenceParametresRoute: typeof AuthenticatedAgenceParametresRoute
  AuthenticatedAgenceProfilRoute: typeof AuthenticatedAgenceProfilRoute
  AuthenticatedAgenceProjetsEnCoursRoute: typeof AuthenticatedAgenceProjetsEnCoursRoute
  AuthenticatedAgenceProspectionRoute: typeof AuthenticatedAgenceProspectionRoute
  AuthenticatedAgenceSuspensionRoute: typeof AuthenticatedAgenceSuspensionRoute
  AuthenticatedAgenceTableauDeBordRoute: typeof AuthenticatedAgenceTableauDeBordRoute
  AuthenticatedAgenceWorkflowRoute: typeof AuthenticatedAgenceWorkflowRoute
  AuthenticatedClientCollaborationsRoute: typeof AuthenticatedClientCollaborationsRoute
  AuthenticatedClientMesProjetsRoute: typeof AuthenticatedClientMesProjetsRouteWithChildren
  AuthenticatedClientMonProfilRoute: typeof AuthenticatedClientMonProfilRoute
  AuthenticatedClientNotificationsRoute: typeof AuthenticatedClientNotificationsRoute
  AuthenticatedClientParametresRoute: typeof AuthenticatedClientParametresRoute
  AuthenticatedClientPostulerUnProjetRoute: typeof AuthenticatedClientPostulerUnProjetRoute
  AuthenticatedClientTableauDeBordRoute: typeof AuthenticatedClientTableauDeBordRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgenceAnalyticsRoute: AuthenticatedAgenceAnalyticsRoute,
  AuthenticatedAgenceFacturationRoute: AuthenticatedAgenceFacturationRoute,
  AuthenticatedAgenceMesProspectionsRoute:
    AuthenticatedAgenceMesProspectionsRoute,
  AuthenticatedAgenceNotificationsRoute: AuthenticatedAgenceNotificationsRoute,
  AuthenticatedAgenceOpportunitesRoute: AuthenticatedAgenceOpportunitesRoute,
  AuthenticatedAgenceParametresRoute: AuthenticatedAgenceParametresRoute,
  AuthenticatedAgenceProfilRoute: AuthenticatedAgenceProfilRoute,
  AuthenticatedAgenceProjetsEnCoursRoute:
    AuthenticatedAgenceProjetsEnCoursRoute,
  AuthenticatedAgenceProspectionRoute: AuthenticatedAgenceProspectionRoute,
  AuthenticatedAgenceSuspensionRoute: AuthenticatedAgenceSuspensionRoute,
  AuthenticatedAgenceTableauDeBordRoute: AuthenticatedAgenceTableauDeBordRoute,
  AuthenticatedAgenceWorkflowRoute: AuthenticatedAgenceWorkflowRoute,
  AuthenticatedClientCollaborationsRoute:
    AuthenticatedClientCollaborationsRoute,
  AuthenticatedClientMesProjetsRoute:
    AuthenticatedClientMesProjetsRouteWithChildren,
  AuthenticatedClientMonProfilRoute: AuthenticatedClientMonProfilRoute,
  AuthenticatedClientNotificationsRoute: AuthenticatedClientNotificationsRoute,
  AuthenticatedClientParametresRoute: AuthenticatedClientParametresRoute,
  AuthenticatedClientPostulerUnProjetRoute:
    AuthenticatedClientPostulerUnProjetRoute,
  AuthenticatedClientTableauDeBordRoute: AuthenticatedClientTableauDeBordRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AgencesRouteChildren {
  AgencesIdRoute: typeof AgencesIdRoute
}

const AgencesRouteChildren: AgencesRouteChildren = {
  AgencesIdRoute: AgencesIdRoute,
}

const AgencesRouteWithChildren =
  AgencesRoute._addFileChildren(AgencesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgencesRoute: AgencesRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  InscriptionAgenceRoute: InscriptionAgenceRoute,
  InscriptionClientRoute: InscriptionClientRoute,
  PostulerUnProjetRoute: PostulerUnProjetRoute,
  ProjetsRoute: ProjetsRoute,
  FonctionnalitesSlugRoute: FonctionnalitesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
